{{- if .Values.prometheus.metrics.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "reposilite.secrets.prometheusBasicAuth.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "reposilite.secrets.prometheusBasicAuth.labels" . | fromYaml) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "reposilite.secrets.prometheusBasicAuth.name" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ default (randAlphaNum 16) .Values.prometheus.metrics.basicAuthPassword }}
  username: {{ default (randAlphaNum 16) .Values.prometheus.metrics.basicAuthUsername }}
{{- end }}
