chart:
  appVersion: 0.1.0
  version: 0.1.0
suite: backendTLSPolicy template
release:
  name: reposilite-unittest
  namespace: testing
templates:
- templates/backendTLSPolicy.yaml
tests:
- it: Skip rendering when disabled 1/6
  set:
    gatewayAPI.enabled: false
    gatewayAPI.core.backendTLSPolicy.enabled: false
    service.enabled: false
  asserts:
  - hasDocuments:
      count: 0

- it: Skip rendering when disabled 2/6
  set:
    gatewayAPI.enabled: true
    gatewayAPI.core.backendTLSPolicy.enabled: false
    service.enabled: false
  asserts:
  - hasDocuments:
      count: 0

- it: Skip rendering when disabled 3/6
  set:
    gatewayAPI.enabled: false
    gatewayAPI.core.backendTLSPolicy.enabled: true
    service.enabled: false
  asserts:
  - hasDocuments:
      count: 0

- it: Skip rendering when disabled 4/6
  set:
    gatewayAPI.enabled: false
    gatewayAPI.core.backendTLSPolicy.enabled: false
    service.enabled: true
  asserts:
  - hasDocuments:
      count: 0

- it: Skip rendering when disabled 5/6
  set:
    gatewayAPI.enabled: true
    gatewayAPI.core.backendTLSPolicy.enabled: false
    service.enabled: true
  asserts:
  - hasDocuments:
      count: 0

- it: Skip rendering when disabled 6/6
  set:
    gatewayAPI.enabled: true
    gatewayAPI.core.backendTLSPolicy.enabled: true
    service.enabled: false
  asserts:
  - hasDocuments:
      count: 0

- it: Render default values
  set:
    gatewayAPI.enabled: true
    gatewayAPI.core.backendTLSPolicy.enabled: true
    service.enabled: true
  asserts:
  - hasDocuments:
      count: 1
  - containsDocument:
      apiVersion: gateway.networking.k8s.io/v1
      kind: BackendTLSPolicy
      name: reposilite-unittest
      namespace: testing
  - contains:
      path: spec.targetRefs
      content:
        group: ""
        kind: Service
        name: reposilite-unittest
  - notExists:
      path: spec.validation.caCertificateRefs

- it: Render with custom annotations and labels
  set:
    gatewayAPI.enabled: true
    gatewayAPI.core.backendTLSPolicy:
      enabled: true
      annotations:
        foo: bar
      labels:
        bar: foo
    service.enabled: true
  asserts:
  - equal:
      path: metadata.annotations
      value:
        foo: bar
  - equal:
      path: metadata.labels
      value:
        app.kubernetes.io/instance: reposilite-unittest
        app.kubernetes.io/name: reposilite
        app.kubernetes.io/version: 0.1.0
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: reposilite-0.1.0
        bar: foo

- it: Render with custom validation
  set:
    gatewayAPI.enabled: true
    gatewayAPI.core.backendTLSPolicy.enabled: true
    gatewayAPI.core.backendTLSPolicy.validation:
      caCertificateRefs:
        - group: ""
          kind: Secret
          name: reposilite-ca
      hostname: reposilite.svc.cluster.local
    service.enabled: true
  asserts:
  - isSubset:
      path: spec.validation
      content:
        caCertificateRefs:
          - group: ""
            kind: Secret
            name: reposilite-ca